### ISSUE TITLE
Setup actuator

### ISSUE THREAD

**Issue by yonatankarp** [yonatankarp/spring-boot-app-template#130]
While actuator dependency is in the project, the actual health check, liveness & readiness are not set.

This issue should set the above by setting the following into the `application.yml` file:

```yml
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - metrics-requiredMetricName
          - prometheus
          - loggers
          - health
          - httptrace
  endpoint:
    health:
      probes.enabled: true
      show-details: always
      livenessState.enabled: true
      readinessState.enabled: true
    metrics.enabled: true
    prometheus.enabled: true
    metrics:
      export.prometheus.enabled: true
      distribution:
        percentiles-histogram.http.server:
          requests: true
        sla.http.server.requests: 50ms, 100ms, 200ms, 400ms
        percentiles.http.server:
          requests: 0.5, 0.9, 0.95, 0.99, 0.999
```
