### ISSUE TITLE
Integrate with CodeQL

### ISSUE THREAD

**Issue by yonatankarp** [yonatankarp/spring-boot-app-template#131]
Add security scan using the open source CodeQL by adding the following workflow under `codeql.yml`:

```yml
name: CodeQL SAST
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codeql-sast:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3

      - name: Install Java
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: 17
          distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@d23060145bc9131d50558d5d4185494a20208101 #v2.12.5
        with:
          languages: 'kotlin'

      - name: Assemble JAR artifact
        id: build_jar
        env:
          GRADLE_USER_HOME: .gradle
        run: ./gradlew assemble

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@d23060145bc9131d50558d5d4185494a20208101 #v2.12.5

```
